# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79397669db1a036fc29b87280e488150625986819e87a7f22b10b4b46e5190be2a696b26da3847ba6240faa0dc9a6b6ff81a3483162b74bc2f5c597e9e73457f

test:
  secret_key_base: aa637ddedd61face842592ee835ec7c50c3de5575b8ae2f77d8409472217066700bd8b227673f7d8066c0de5a825de67e9fdc135c9600b090298ce732013e842

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
